### ISSUE TITLE
Use navigation instead of toolbar

### ISSUE THREAD

**Issue by leoj3n** [khan4019/superior150#2]
@khan4019 Can we make it look more like this?

![image](https://cloud.githubusercontent.com/assets/990216/26041995/14d937a8-38f7-11e7-8591-b1e4204d648d.png)

https://material.angularjs.org/latest/demo/navBar

**Comment by khan4019** [comment]
We can do it very easily... 
I will do it tonight...

**Comment by leoj3n** [comment]
![](https://giphy.com/gifs/happy-spongebob-squarepants-patrick-TdfyKrN7HGTIY)

**Comment by leoj3n** [comment]
![](https://media.giphy.com/media/TdfyKrN7HGTIY/giphy.gif)
